#!/usr/bin/python3

# GET BRANCH NAME
# git symbolic-ref -q HEAD

import sys
import os
import socket
import subprocess
from util import color, get_branch_name, get_commit_hash, get_stdin_input, extract_branch_name, cmd

print(color.pink('=============DEV_POST_MERGE_HOOK================'))
print(color.yellow(str(sys.argv)))
