#!/usr/bin/python3

# GET BRANCH NAME
# git symbolic-ref -q HEAD

import sys
import os
import socket
import subprocess
from util import color, get_branch_name, get_commit_hash, get_stdin_input, extract_branch_name, cmd

print(color.pink('=============DEV_POST_MERGE_HOOK================'))
print(color.yellow(str(sys.argv)))
input = get_stdin_input()
print(color.yellow(str(input)))
command = cmd(['ps', '-o', 'args='+str(os.getppid())])
print(command.splitlines())
print(command[2])
if command[2].startswith('git pull'):
    print('It is pull!')
elif command[2].startswith('git merge'):
    print('It is merge with ', command[2].strip("git merge "))

# Check multi commit merge
# Solve git fetch hook

'''
1302
/bin/bash
git pull
/usr/lib/git-core/git merge FETCH_HEAD
/usr/bin/python3 ../hooks/dev/post-merge 0
ps -o args=1302

1353
/bin/bash
git merge branch1
/usr/bin/python3 ../hooks/dev/post-merge 0
ps -o args=1353
'''