#!/usr/bin/python3

"""
    This hook happens after commit

    This hook creates .git/[commit_hash].sql difference file
    Between developer database and remote branch database
    Later during push this file will be applied to branch database in pre-push hook

    Also commit will revert if diff file generation fails

    To allow empty commits use:
    git commit --allow-empty -a -m "my commit message"
"""

import sys
import os
import socket
import subprocess
from util import color, cmd, diff_file_path, get_branch_name, get_commit_hash, pg_sync, undo_commit


branch_name = get_branch_name()

pg_sync(pg_from_env='pg_dev', 
        pg_to_env='pg_branch', 
        pg_from_db=branch_name, 
        pg_to_db=branch_name, 
        pg_sql_file=diff_file_path('push'),
        pg_apply=False)

# Create new branch and commit (?)
#   Maybe post-checkout hook will do it